title: Akshath Jain
email: akshath@akshathjain.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Akshath Jain. Welcome to my website! 
  I'm an avid Android Developer, programmer, and 
  artificial intelligence aficionado. I'm currently 
  a freshman at Carnegie Mellon University studying 
  Computer Science, and I enjoy running and playing 
  tennis. Feel free to take a look around my site 
  and view some of the projects that I've done!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  akshathjain
instagram_username: akshath_jain
twitter_username: akshathjain01

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed